module.exports = {
    src: [
        "scripts/app.js",
        "config.js",
        "scripts/whitelabel/WhitelabelColorsLogoCtrl.js",
        "scripts/**/*.js",
        // Don't include these
        "!scripts/services/cfcallflow.js",
        "!scripts/services/compdata.js",
        "!scripts/services/model.js",
        "!scripts/report/summary_report.js",
        "!scripts/chart/dashboard.js"
    ],

    lazyLoaded: [
        "bower_components/jquery.inputmask/dist/jquery.inputmask.bundle.js"

    ],
    tests: [
        "lib_modified/angular-mocks.js",
        "tests/**/*.js"
    ],

    grunt_stuff: [
        "Gruntfile.js",
        "grunt/**/*.js",
        "karma.conf.js"
    ],

    vendor: [
        "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js",
        "bower_components/modernizr/modernizr.js",
        "bower_components/underscore/underscore.js",
		"bower_components/angular/angular.js",
		"bower_components/angular-resource/angular-resource.js",
		"bower_components/angular-cookies/angular-cookies.js",
		"bower_components/angular-sanitize/angular-sanitize.js",
		"bower_components/angular-route/angular-route.js",
		"bower_components/angular-animate/angular-animate.js",
		"https://cdnjs.cloudflare.com/ajax/libs/angular-material/1.1.1/angular-material.min.js",
        "bower_components/bootstrap/dist/js/bootstrap.js",
        "bower_components/seiyria-bootstrap-slider/js/bootstrap-slider.js",
        "bower_components/angular-bootstrap/ui-bootstrap-tpls.js",
        "bower_components/jquery.ui/ui/jquery-ui.js",
        "bower_components/jquery.ui/ui/jquery.ui.widget.js",
        "bower_components/jquery.ui/ui/jquery.ui.mouse.js",
        "bower_components/jquery.slimscroll/jquery.slimscroll.js",
        "bower_components/jquery.easing/js/jquery.easing.min.js",
        "bower_components/flot/jquery.flot.js",
        "bower_components/flot/jquery.flot.stack.js",
        "bower_components/flot/jquery.flot.pie.js",
        "bower_components/flot/jquery.flot.resize.js",
        "bower_components/flot.tooltip/js/jquery.flot.tooltip.js",
        "bower_components/angular-ui-tree/dist/angular-ui-tree.js",
		"js/angular-sticky-table-header2.js",
		"js/angular-sticky-table-header3.js",
		"bower_components/watch-dom/dist/watch-dom.js",
        "bower_components/moment/moment.js",
		"bower_components/smDateTimeRangePicker/src/picker.js",
        "bower_components/angular-toggle-switch/angular-toggle-switch.min.js",
        "bower_components/ng-grid/build/ng-grid.js",
        "bower_components/angular-xeditable/dist/js/xeditable.js",
        "bower_components/select2/select2.js",
        "bower_components/angular-ui-select2/src/select2.js",
        "bower_components/iCheck/icheck.min.js",
        "bower_components/bootbox.js/bootbox.js",
        "bower_components/jquery-autosize/jquery.autosize.js",
        "bower_components/jquery.pulsate/jquery.pulsate.js",
        "bower_components/jquery.knob/js/jquery.knob.js",
        "bower_components/jquery.sparkline/index.js",
        "bower_components/flow.js/dist/flow.js",
        "bower_components/ng-flow/dist/ng-flow.js",
        "bower_components/jScrollPane/script/jquery.jscrollpane.min.js",
        "bower_components/enquire/dist/enquire.js",
        "bower_components/pnotify/pnotify.core.js",
        "bower_components/pnotify/pnotify.buttons.js",
        "bower_components/pnotify/pnotify.callbacks.js",
        "bower_components/pnotify/pnotify.confirm.js",
        "bower_components/pnotify/pnotify.desktop.js",
        "bower_components/pnotify/pnotify.history.js",
        "bower_components/pnotify/pnotify.nonblock.js",
        "bower_components/Caret.js/dist/jquery.caret.js",
        "bower_components/Caret.js/dist/jquery.caret.min.js",
        "bower_components/angular-disable-all/dist/angular-disable-all.js",
        "bower_components/angular-utils-pagination/dirPagination.js",
        "bower_components/excellentexport/excellentexport.js",
        "bower_components/ng-csv/build/ng-csv.js",
        "bower_components/raphael/raphael.js",
        "bower_components/morris.js/morris.js",
        "bower_components/ng-file-upload/angular-file-upload-shim.js",
        "bower_components/ng-file-upload/angular-file-upload.js",
        "bower_components/jquery-highlighttextarea/jquery.highlighttextarea.min.js",

        "bower_components/canvg/dist/canvg.js",
        "bower_components/html2canvas/build/html2canvas.js",
        "bower_components/jspdf/dist/jspdf.debug.js",

        'bower_components/jquery-validation/dist/jquery.validate.js',
        'bower_components/stepy/lib/jquery.stepy.js',
        'bower_components/jquery.inputmask/dist/jquery.inputmask.bundle.js',
        'assets/plugins/ckeditor/ckeditor.js',
        'assets/plugins/ckeditor/plugins/strinsert/plugin.js',
        'assets/plugins/ckeditor/lang/en.js',

        "assets/plugins/form-daterangepicker/daterangepicker.min.js",
        "assets/plugins/form-datepicker/js/bootstrap-datepicker.js",
        "assets/plugins/easypiechart/angular.easypiechart.js",
        "assets/plugins/datepaginator/bootstrap-datepaginator.js",
        "assets/plugins/form-multiselect/js/jquery.multi-select.min.js",
        "assets/plugins/form-colorpicker/js/bootstrap-colorpicker.min.js",
        "assets/plugins/form-fseditor/jquery.fseditor-min.js",
        "assets/plugins/form-jasnyupload/fileinput.js",
        "assets/plugins/gridster/jquery.gridster.min.js",
        "assets/plugins/progress-skylo/skylo.js",
        "assets/plugins/bootstro.js/bootstro.min.js",
        "assets/plugins/ngInfiniteScroll-1.0.0/build/ng-infinite-scroll.js",

        "scripts/services/report.js",
        "scripts/chart/CallFlows.js",
        "scripts/pages/EmailDigestBuilder.js",
        "scripts/shared/Services.js",
        "scripts/shared/Directives.js",
        "scripts/maps/VectorMaps.js",
        "scripts/calendar/Calendar.js",
        "scripts/gallery/Gallery.js",
        "scripts/ui-components/Tiles.js",
        "scripts/ui-components/Alerts.js",
        "scripts/ui-components/Sliders.js",
        "scripts/ui-components/Paginations.js",
        "scripts/ui-components/Tabs.js",
        "scripts/ui-components/Nestable.js",
        "scripts/ui-elements/Tables.js",
        "scripts/ui-elements/Panels.js",
        "scripts/form/Components.js",
        "scripts/form/Directives.js",
        "scripts/form/Validation.js",
        "scripts/form/Inline.js",
        "scripts/form/ImageCrop.js",
        "scripts/table/ngGrid.js",

        "scripts/table/Editable.js",
        "scripts/chart/Flot.js",
        "scripts/chart/SVG.js",
        "scripts/chart/Canvas.js",
        "scripts/chart/Inline.js",
        "scripts/layout/Horizontal.js",
        "scripts/login/Controllers.js",
        "scripts/templates/templates.js",
        "scripts/templates/overrides.js",
        "scripts/controllers/Navigation.js",
        "scripts/controllers/Notifications.js",
        "scripts/controllers/Messages.js",
        "scripts/controllers/Dashboard.js",
        "scripts/report/call_flow.js",
        "scripts/report/campaign.js",
        "scripts/calldetails/callsdetails.js",
        "scripts/controllers/cfcontroller.js",
        "scripts/org_unit/org_unit.js",
        "scripts/subscriptions/subscriptions.js",
        "scripts/ui-components/Modals.js",
		"scripts/report/advFilSrvc.js",
		"scripts/distribution_list/distribution_list.js",
		"scripts/distribution_list/distribution_list_webservice.js",
		"scripts/scheduledreport/scheduledreports.js",
		"scripts/scheduledreport/scheduledreports_webservice.js",

        "js/d3.js",
        "js/crossfilter.js",
        "js/colorbrewer.js",
        "js/barchart.js",
        "js/angular-idle.js",

        "/lib/absolute.js",
        "/lib/dc.js",
        "node_modules/ng-idle/angular-idle.js"
    ]
};
